#!/usr/bin/env python3
"""Talk to the serial test commands of the sensecap_watcher example.

  serial_test.py PORT send clip.wav     transcribe a WAV on the device (16kHz mono 16-bit, max 8.3s)
  serial_test.py PORT say "some text"   same, with speech generated by macOS `say`
  serial_test.py PORT dump out.wav      save the last knob recording (what the model heard)
  serial_test.py PORT rec "some text"   hold the knob from here, speak the text through the Mac's
                                        speakers, show what the device heard, save it to rec.wav

Needs pyserial (the ESP-IDF Python environment has it). Close idf.py monitor first.
"""
import argparse
import os
import subprocess
import sys
import tempfile
import time
import wave

import serial

RATE = 16000
MAX_SAMPLES = 5760 * 23
# The Watcher's CH342 USB-serial chip (with the macOS driver) drops writes of exactly
# 64 bytes, so send in smaller pieces
CHUNK = 63


def open_port(port):
    s = serial.Serial(port, 115200, timeout=0.5)
    # Opening the port can pulse DTR/RTS and reset the chip; wait for it to boot
    s.dtr = False
    s.rts = False
    time.sleep(0.2)
    s.reset_input_buffer()
    return s


def read_until(s, prefixes, timeout):
    """Returns the first line starting with one of prefixes, echoing the device log meanwhile."""
    end = time.time() + timeout
    while time.time() < end:
        line = s.readline().decode("utf-8", "replace").rstrip()
        if not line:
            continue
        if line.startswith(prefixes):
            return line
        print(f"  | {line}")
    sys.exit(f"timed out waiting for {prefixes}")


def command(s, cmd, expect, timeout=20):
    """Sends cmd until the device answers; the first try may land while it still boots."""
    for _ in range(3):
        s.write(cmd)
        try:
            return read_until(s, expect, timeout)
        except SystemExit:
            print("  (no answer, retrying)")
    sys.exit("device does not answer, is the sensecap_watcher example running?")


def load_wav(path):
    with wave.open(path, "rb") as w:
        if w.getnchannels() != 1 or w.getsampwidth() != 2 or w.getframerate() != RATE:
            sys.exit(f"{path}: need 16kHz mono 16-bit, got {w.getframerate()}Hz "
                     f"{w.getnchannels()}ch {8 * w.getsampwidth()}-bit\n"
                     f"convert with: afconvert -f WAVE -d LEI16@16000 -c 1 in.wav out.wav")
        return w.readframes(w.getnframes())


def send(s, pcm):
    n = len(pcm) // 2
    if n > MAX_SAMPLES:
        print(f"clip is {n / RATE:.1f}s, cutting to {MAX_SAMPLES / RATE:.1f}s")
        n = MAX_SAMPLES
        pcm = pcm[:2 * n]
    print(f"sending {n / RATE:.2f}s of audio")
    command(s, f"PCM {n}\n".encode(), ("READY", "ERR"))
    t0 = time.time()
    for i in range(0, len(pcm), CHUNK):
        s.write(pcm[i:i + CHUNK])
    s.flush()
    got = read_until(s, ("GOT", "ERR"), 60)
    print(f"  {got}  (sent in {time.time() - t0:.1f}s, expected sum {sum(pcm)})")
    line = read_until(s, ("TIME", "ERR"), 60)
    if line.startswith("ERR"):
        sys.exit(line)
    text = read_until(s, ("TEXT:",), 5)
    print(f"transcribed in {line.split()[1]}s")
    print(text)


def dump(s, path):
    header = command(s, b"DUMP\n", ("DUMP",))
    n = int(header.split()[1])
    data = bytearray()
    while True:
        line = s.readline().decode().strip()
        if line == "END":
            break
        data += bytes.fromhex(line)
    if len(data) != 2 * n:
        sys.exit(f"got {len(data) // 2} of {n} samples")
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(data)
    samples = memoryview(bytes(data)).cast("h")
    peak = max((abs(x) for x in samples), default=0)
    print(f"saved {n / RATE:.2f}s to {path}, peak level {peak}")


def rec(s, text, path="rec.wav"):
    # Measure how long the speech is, then hold the virtual knob a bit longer than that
    with tempfile.TemporaryDirectory() as d:
        clip = os.path.join(d, "say.wav")
        subprocess.run(["say", "-o", clip, "--file-format=WAVE", "--data-format=LEI16@16000", text], check=True)
        with wave.open(clip, "rb") as w:
            secs = w.getnframes() / w.getframerate()
    hold_ms = min(int((secs + 1.0) * 1000), MAX_SAMPLES * 1000 // RATE - 200)
    command(s, f"REC {hold_ms}\n".encode(), ("OK",))
    time.sleep(0.3)
    subprocess.run(["say", text], check=True)
    end = time.time() + hold_ms / 1000 + 30
    while time.time() < end:
        line = s.readline().decode("utf-8", "replace").rstrip()
        if line:
            print(f"  | {line}")
        if "Heard" in line or "Transcription failed" in line:
            break
    dump(s, path)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("port")
    p.add_argument("cmd", choices=["send", "say", "dump", "rec"])
    p.add_argument("arg")
    a = p.parse_args()

    s = open_port(a.port)
    if a.cmd == "send":
        send(s, load_wav(a.arg))
    elif a.cmd == "say":
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "say.wav")
            subprocess.run(["say", "-o", path, "--file-format=WAVE", "--data-format=LEI16@16000", a.arg],
                           check=True)
            send(s, load_wav(path))
    elif a.cmd == "rec":
        rec(s, a.arg)
    else:
        dump(s, a.arg)


if __name__ == "__main__":
    main()
